#!/usr/bin/env node
'use strict';
/*
 * Two generated files, no bundler.
 *
 *   public/js/core-bundle.js   src/*.js wrapped in a four-line CommonJS shim so
 *                              the browser can run the exact same engine, bot,
 *                              room manager and protocol the server runs — and
 *                              the test suite keeps covering the shipped code.
 *   public/js/config.js        where the client should look for a room server.
 *
 * ROOM_SERVER_URL:
 *   unset, local        ""      the page's own origin (a normal `npm start`)
 *   unset, on Vercel    null    static deploy, no backend -> bot play only
 *   set                 <url>   e.g. https://camel-and-coin.onrender.com
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'public', 'js');
const MODULES = ['rules', 'engine', 'bot', 'rooms', 'session'];   // dependency order

function bundle() {
  const parts = [
    '/* GENERATED by scripts/build.js — do not edit. Source of truth: src/*.js */',
    '(function (global) {',
    '  "use strict";',
    '  var __mods = {};',
    '  function require(id) {',
    '    var key = String(id).replace(/^\\.\\//, "").replace(/\\.js$/, "");',
    '    if (!(key in __mods)) throw new Error("core-bundle: unknown module " + id);',
    '    return __mods[key];',
    '  }',
  ];

  for (const name of MODULES) {
    const src = fs.readFileSync(path.join(ROOT, 'src', `${name}.js`), 'utf8');
    parts.push(
      `  __mods[${JSON.stringify(name)}] = (function () {`,
      '    var module = { exports: {} }, exports = module.exports;',
      src.replace(/^/gm, '    '),
      '    return module.exports;',
      '  })();'
    );
  }

  parts.push('  global.GameCore = __mods;', '})(typeof self !== "undefined" ? self : this);', '');
  return parts.join('\n');
}

function config() {
  const explicit = (process.env.ROOM_SERVER_URL || '').trim();
  // Anywhere we are built for a static host, "no room server" is the right
  // default — only a local run or the room server itself may claim its origin.
  const staticHost = process.env.VERCEL || process.env.GITHUB_ACTIONS || process.env.CI;
  let value;
  if (explicit) value = JSON.stringify(explicit.replace(/\/+$/, ''));
  else if (staticHost) value = 'null';
  else value = '""';

  return `/* GENERATED by scripts/build.js — do not edit. */
/* "" = this page's own origin · null = no room server, bot play only */
window.ROOM_SERVER_URL = ${value};
`;
}

fs.mkdirSync(OUT, { recursive: true });
fs.writeFileSync(path.join(OUT, 'core-bundle.js'), bundle());
fs.writeFileSync(path.join(OUT, 'config.js'), config());

const kb = (f) => (fs.statSync(path.join(OUT, f)).size / 1024).toFixed(1) + ' kB';
const room = (process.env.ROOM_SERVER_URL || '').trim()
  || ((process.env.VERCEL || process.env.GITHUB_ACTIONS || process.env.CI)
    ? '(none — bot play only)' : '(this origin)');
console.log(`  core-bundle.js  ${kb('core-bundle.js')}  (${MODULES.join(', ')})`);
console.log(`  config.js       ${kb('config.js')}  room server: ${room}`);
