#!/usr/bin/env node
'use strict';
/*
 * Two generated files, no bundler.
 *
 *   public/js/core-bundle.js   src/*.js wrapped in a four-line CommonJS shim so
 *                              the browser can run the exact same engine, bot,
 *                              room manager and protocol the server runs — and
 *                              the test suite keeps covering the shipped code.
 *   public/js/config.js        where the client should look for a room server.
 *
 * ROOM_SERVER_URL:
 *   unset, local          ""      the page's own origin (a normal `npm start`)
 *   unset, on a static    null    no backend -> bot play only, and the menu
 *     host (Vercel,               says so instead of failing on click
 *     Pages, Netlify)
 *   "same-origin"         ""      this deploy serves page and rooms together
 *   <url>                 <url>   rooms live on another host
 */

const fs = require('fs');
const path = require('path');

// A deploy that hosts the whole game — page and rooms together — sets
// ROOM_SERVER_URL to this, which is clearer than relying on an empty string.
const SAME_ORIGIN = 'same-origin';

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'public', 'js');
const MODULES = ['rules', 'engine', 'bot', 'rooms', 'session'];   // dependency order

function bundle() {
  const parts = [
    '/* GENERATED by scripts/build.js — do not edit. Source of truth: src/*.js */',
    '(function (global) {',
    '  "use strict";',
    '  var __mods = {};',
    '  function require(id) {',
    '    var key = String(id).replace(/^\\.\\//, "").replace(/\\.js$/, "");',
    '    if (!(key in __mods)) throw new Error("core-bundle: unknown module " + id);',
    '    return __mods[key];',
    '  }',
  ];

  for (const name of MODULES) {
    const src = fs.readFileSync(path.join(ROOT, 'src', `${name}.js`), 'utf8');
    parts.push(
      `  __mods[${JSON.stringify(name)}] = (function () {`,
      '    var module = { exports: {} }, exports = module.exports;',
      src.replace(/^/gm, '    '),
      '    return module.exports;',
      '  })();'
    );
  }

  parts.push('  global.GameCore = __mods;', '})(typeof self !== "undefined" ? self : this);', '');
  return parts.join('\n');
}

function config() {
  const explicit = (process.env.ROOM_SERVER_URL || '').trim();

  // Named static hosts only. A generic CI=true would wrongly cover the room
  // server's own build — the one deploy that *does* serve its own rooms.
  const staticHost = process.env.VERCEL || process.env.GITHUB_ACTIONS
    || process.env.NETLIFY || process.env.CF_PAGES;

  let value;
  if (explicit === SAME_ORIGIN) value = '""';                 // "I serve my own rooms"
  else if (explicit) value = JSON.stringify(explicit.replace(/\/+$/, ''));
  else if (staticHost) value = 'null';
  else value = '""';

  return `/* GENERATED by scripts/build.js — do not edit. */
/* "" = this page's own origin · null = no room server, bot play only */
window.ROOM_SERVER_URL = ${value};
`;
}

fs.mkdirSync(OUT, { recursive: true });
fs.writeFileSync(path.join(OUT, 'core-bundle.js'), bundle());
fs.writeFileSync(path.join(OUT, 'config.js'), config());

const kb = (f) => (fs.statSync(path.join(OUT, f)).size / 1024).toFixed(1) + ' kB';
const chosen = JSON.parse(config().match(/= (.*);/)[1]);
const room = chosen === null ? '(none — bot play only)'
  : chosen === '' ? '(this origin — rooms served here)'
  : chosen;
console.log(`  core-bundle.js  ${kb('core-bundle.js')}  (${MODULES.join(', ')})`);
console.log(`  config.js       ${kb('config.js')}  room server: ${room}`);
